apiVersion: cs.opensourceways.com/v1alpha1
kind: CodeServer
metadata:
  name: codeserver-husheng
spec:
  runtime: code
  subdomain: codeservertommy
  image: "codercom/code-server:4.7.1"
  storageSize: "1Gi"
  storageName: "emptyDir"
  inactiveAfterSeconds: 120
  recycleAfterSeconds: 240
  readinessProbe:
    httpGet:
      path: "/active-time"
      port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
    timeoutSeconds: 3
  envs:
    - name: PASSWORD
      value: "12345678"
  resources:
    requests:
      cpu: "2"
      memory: "2048m"
  connectProbe: "/active-time"
