# permissions for end users to edit codeservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codeserver-editor-role
rules:
- apiGroups:
  - cs.opensourceways.com
  resources:
  - codeservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cs.opensourceways.com
  resources:
  - codeservers/status
  verbs:
  - get
